### ISSUE TITLE
Home Assistant version 23.20.0 Modbus Keyword "Count" depreciation.

### ISSUE THREAD

**Issue by nilremgithub** [fboundy/ha_solis_modbus#17]
It seems the keyword count no longer supported for the data types  int16 or uint16 or int32 or uint32 in the solis.yaml file. Further info here: https://github.com/home-assistant/core/issues/101421

**Comment by mrstevefay** [comment]
Is their a fix for this we can implement?

**Comment by lorrainem77** [comment]
In the modbus yaml file, find all "count:" lines and either put a # in front of it (e.g. #count: 1) or just remove the line

**Comment by fboundy** [comment]
Yes, that’s correct. Will update the repo when I get a minute

**Comment by Paulholloway** [comment]
I'm genuinely putting off ever doing another core update... This is the second time in a row that they've broken modbus!

**Comment by fboundy** [comment]
Closed with release 2.0.0

**Comment by joeczucha** [comment]
> Closed with release 2.0.0

Just a heads up that where you've done a find/replace on `count:` you've also caught `lazy_count:` so now your solis.yaml is reading: `lazy_error_# count: 5` and throwing errors.

Otherwise, great project :)

**Comment by fboundy** [comment]
Doh! That’ll teach me. Will get it fixed asap.

**Comment by fboundy** [comment]
Now fixed
