### ISSUE TITLE
Solis Daily Import/Export no longer appear to reset

### ISSUE THREAD

**Issue by Paulholloway** [fboundy/ha_solis_modbus#23]
Having just updated to HA Core 2024.4.0 yesterday, I've just this morning noticed that my Solis Daily Import/Export entities have continued to increment beyond midnight.  

<img width="1739" alt="Screenshot 2024-04-05 at 04 46 40" src="https://github.com/fboundy/ha_solis_modbus/assets/127039002/6d184967-b15b-427a-bcef-e48dee4058f8">

I'm not sure if this is a quirk, coincidence, or if I've just caught HA at the wrong time, but historical data showed a clear reset to zero at midnight.  

I'm very much open to this being an ill-timed HA update, but otherwise - Thoughts welcome!

**Comment by fboundy** [comment]
These entities come directly from the inverter so I suspect it’s a Solis issue rather than an HA issue. I’m not seeing this with either Solax or HA core integrations bi TV I haven’t upgraded yet (always wait until at least x.x.1 to flush out bugs…)

**Comment by Paulholloway** [comment]
Spot on and super quick response.  A quick look at the value of [solis day RW](url) reveals it was seemingly upset by the clocks changing.  Forcing an update to register 43002 fixed this, and my daily values have reset to zero.  

<img width="424" alt="Screenshot 2024-04-05 at 07 22 06" src="https://github.com/fboundy/ha_solis_modbus/assets/127039002/ff8e91aa-d532-4171-95c5-584330efffb5">
<img width="1746" alt="Screenshot 2024-04-05 at 07 20 05" src="https://github.com/fboundy/ha_solis_modbus/assets/127039002/1a1e4ab9-f8c8-47be-af7b-7e21fa84b3b2">
