### ISSUE TITLE
Solis Total Generation has wrong state class

### ISSUE THREAD

**Issue by finalbillybong** [fboundy/ha_solis_modbus#3]
sensor.solis_total_generation should have a state class of 'total_increasing' to work correctly with Home Assistant Energy Dashboard.

**Comment by fboundy** [comment]
I think this actually only needs to be on the daily totals as these reset to zero. They should then work directly in the Energy Dashboard:

[HA Doccumentation](https://developers.home-assistant.io/blog/2021/08/16/state_class_total/)
