### ISSUE TITLE
script.yaml - any value under exampled e.g. example: 50   - shows teh numebr as an error

### ISSUE THREAD

**Issue by Bignose3** [fboundy/ha_solis_modbus#9]
Hi,

I think I have asked too early, should be able figure more out so ignore below, I guess the example it to be ignored/removed  & use the input value to be set in HA.

Really sorry to ask this as guess should be obvious & does NOT prevent from starting but have found any errors marked can cause problems later on.
on all the numbers after "example:" are marked as an error. red squiggle under each number.
using VS HA helper.
e.g.
solis_set_charge_current:
  alias: Solis Set Charge Current
  fields:
    solis_set_charge_current:
      description: Fixed time charge current (A)
      example: 50

I am actually struggling to get it to work at all from HA, I can read all the data from previous info. great, no problems.
Just trying to set up to send.

**Comment by fboundy** [comment]
I don't think this is an issue. `example` is defined [here](https://www.home-assistant.io/integrations/script/) as an optional parameter.
